### ISSUE TITLE
Bump repo to `forc 0.31.1` and `fuels 0.31.1`

### ISSUE THREAD

**Issue by supiket** [FuelLabs/sway-applications#294]
### Motivation

The AMM scripts #267 and #288 use a PR on the `fuels-rs` repo that uses the updated versions of `forc` and `fuels`. The apps should be updated to the latest versions.

**Comment by simonr0204** [comment]
In the roadmap meeting someone mentioned we could split the work between several of us. This makes sense since each person will be most familiar with the applications they wrote. We could create a single branch for the version bump and have several contributors: since each app is independent, there shouldn't be any conflicts.

**Comment by supiket** [comment]
> In the roadmap meeting someone mentioned we could split the work between several of us. This makes sense since each person will be most familiar with the applications they wrote. We could create a single branch for the version bump and have several contributors: since each app is independent, there shouldn't be any conflicts, we just need to coordinate who is working on what. Maybe we could add a "sign-up list" to the issue?

I will bring this up in tomorrow's sync to let everybody know and to discuss.
