### ISSUE TITLE
Vault

### ISSUE THREAD

**Issue by Braqzen** [FuelLabs/sway-applications#95]
### Application Description

A vault is a contract that accepts a deposit from a user and tracks the number of shares the user should receive in proportion to their deposit with respect to the total supply in the vault.

The deposits made into the vault are used by the vault owners in order to generate a yield and return some portion to the user in accordance to their shares as an incentive to deposit in the first place.

When a user withdraws they specify a number of shares they wish to withdraw which transfers back to them an amount that is calculated relative to their shares and the total supply (and not simply whatever they have deposited).

Note: It has been suggested to be compliant with [EIP-4626](https://eips.ethereum.org/EIPS/eip-4626)

### Features

- [ ] #112
- [ ] #113
- [ ] #114

**Comment by nfurfaro** [comment]
I think aiming (mostly) for compliance with EIP-4626 is a good start. I say mostly because the use of native assets on Fuel introduces some differences in how we do things. 
One example is that EIP-4626 is an extension of the ERC-20 token contract, which itself has a few things that need to be reconsidered in light of native assets (i.e: `approvals`, `transferFrom`, allowances, etc...).

**Comment by SwayStar123** [comment]
Closed as this app is no longer being worked on

**Comment by SwayStar123** [comment]
The SRC6 vault standard has example implementations 
https://github.com/FuelLabs/sway-standards/
